# Generated by Django 3.1.2 on 2020-10-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20201025_0749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['day_to_perform']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='day_of_completion',
            new_name='day_to_perform',
        ),
        migrations.AddField(
            model_name='task',
            name='execution_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('DL', 'Deleted'), ('NW', 'New'), ('EXP', 'Expired'), ('OK', 'Completed')], default='NW', max_length=3),
        ),
    ]
